# iOS Agent 客户端 - CocoaPods 配置
# 使用: pod install 后打开 iOSAgentApp.xcworkspace

platform :ios, '15.0'
use_frameworks!

target 'iOSAgentApp' do
  pod 'YYText'   # 高性能富文本，解决长文 cell 卡顿
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end
