# Mac Agent 客户端 - CocoaPods 配置
# 使用: pod install 后打开 MacAgentApp.xcworkspace

platform :osx, '12.0'
use_frameworks!

target 'MacAgentApp' do
  # 可按需添加更多依赖，例如:
  # pod 'Alamofire'           # 网络请求
  # pod 'SnapKit'             # Auto Layout (Swift)
  # pod 'Kingfisher'          # 图片加载
  # pod 'CocoaLumberjack'     # 日志
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
